FROM python:3.10.10-alpine
ENV PYTHONUNBUFFERED 1

# Build-time metadata as defined at http://label-schema.org
ARG OPAC_BUILD_DATE
ARG OPAC_VCS_REF
ARG OPAC_WEBAPP_VERSION

ENV OPAC_BUILD_DATE ${OPAC_BUILD_DATE}
ENV OPAC_VCS_REF ${OPAC_VCS_REF}
ENV OPAC_WEBAPP_VERSION ${OPAC_WEBAPP_VERSION}

LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name="OPAC WebApp - development build" \
      org.label-schema.description="OPAC WebApp main app" \
      org.label-schema.url="https://github.com/scieloorg/opac/" \
      org.label-schema.vcs-ref=$OPAC_VCS_REF \
      org.label-schema.vcs-url="https://github.com/scieloorg/opac/" \
      org.label-schema.vendor="SciELO" \
      org.label-schema.version=$OPAC_WEBAPP_VERSION \
      org.label-schema.schema-version="1.0"

RUN apk --update add --no-cache \
    git gcc build-base zlib-dev jpeg-dev curl libxml2-dev libxslt-dev py3-lxml


COPY ./requirements.txt /app/requirements.txt
COPY ./requirements.dev.txt /app/requirements.dev.txt
COPY ./start_worker.sh /start_worker.sh
COPY ./start_scheduler.sh /start_scheduler.sh


RUN sed -i 's/\r//' /start_worker.sh \
    && sed -i 's/\r//' /start_scheduler.sh \
    && chmod +x /start_worker.sh \
    && chmod +x /start_scheduler.sh \
    && chown nobody /start_worker.sh \
    && chown nobody /start_scheduler.sh

RUN pip --no-cache-dir install -r /app/requirements.txt && \
    pip --no-cache-dir install -r /app/requirements.dev.txt
RUN chown -R nobody:nogroup /app
USER nobody

EXPOSE 8000
WORKDIR /app

HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl -f http://localhost:8000/ || exit 1

CMD gunicorn --worker-class=gevent --worker-connections=1000 --workers 3 --bind 0.0.0.0:8000 manager:app --chdir=/app/opac --log-level DEBUG

