FROM python:3.5
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /app/requirements.txt
COPY ./requirements.dev.txt /app/requirements.dev.txt

RUN pip install -r /app/requirements.txt && \
    pip install -r /app/requirements.dev.txt

USER nobody

EXPOSE 8000
WORKDIR /app

CMD gunicorn --workers 3 --bind 0.0.0.0:8000 manager:app --chdir=/app/opac --log-level DEBUG
