FROM python:3.5-alpine
ENV PYTHONUNBUFFERED 1

RUN apk --update add --no-cache \
    git gcc build-base zlib-dev jpeg-dev


COPY ./requirements.txt /app/requirements.txt
COPY ./requirements.dev.txt /app/requirements.dev.txt

RUN pip --no-cache-dir install -r /app/requirements.txt && \
    pip --no-cache-dir install -r /app/requirements.dev.txt

USER nobody

EXPOSE 8000
WORKDIR /app

CMD gunicorn --workers 3 --bind 0.0.0.0:8000 manager:app --chdir=/app/opac --log-level DEBUG
