LANG_NAMES = {
    "ab": (u"аҧсуа бызшәа, аҧсшәа", u"Abkhazian"),
    "aa": (u"Afaraf", u"Afar"),
    "af": (u"Afrikaans", u"Afrikaans"),
    "ak": (u"Akan", u"Akan"),
    "sq": (u"Shqip", u"Albanian"),
    "am": (u"አማርኛ", u"Amharic"),
    "ar": (u"العربية", u"Arabic"),
    "an": (u"aragonés", u"Aragonese"),
    "hy": (u"Հայերեն", u"Armenian"),
    "as": (u"অসমীয়া", u"Assamese"),
    "av": (u"авар мацӀ, магӀарул мацӀ", u"Avaric"),
    "ae": (u"avesta", u"Avestan"),
    "ay": (u"aymar aru", u"Aymara"),
    "az": (u"azərbaycan dili", u"Azerbaijani"),
    "bm": (u"bamanankan", u"Bambara"),
    "ba": (u"башҡорт теле", u"Bashkir"),
    "eu": (u"euskara, euskera", u"Basque"),
    "be": (u"беларуская мова", u"Belarusian"),
    "bn": (u"বাংলা", u"Bengali"),
    "bh": (u"भोजपुरी", u"Bihari languages"),
    "bi": (u"Bislama", u"Bislama"),
    "bs": (u"bosanski jezik", u"Bosnian"),
    "br": (u"brezhoneg", u"Breton"),
    "bg": (u"български език", u"Bulgarian"),
    "my": (u"ဗမာစာ", u"Burmese"),
    "ca": (u"català, valencià", u"Catalan, Valencian"),
    "ch": (u"Chamoru", u"Chamorro"),
    "ce": (u"нохчийн мотт", u"Chechen"),
    "ny": (u"chiCheŵa, chinyanja", u"Chichewa, Chewa, Nyanja"),
    "zh": (u"中文 (Zhōngwén), 汉语, 漢語", u"Chinese"),
    "cv": (u"чӑваш чӗлхи", u"Chuvash"),
    "kw": (u"Kernewek", u"Cornish"),
    "co": (u"corsu, lingua corsa", u"Corsican"),
    "cr": (u"ᓀᐦᐃᔭᐍᐏᐣ", u"Cree"),
    "hr": (u"hrvatski jezik", u"Croatian"),
    "cs": (u"čeština, český jazyk", u"Czech"),
    "da": (u"dansk", u"Danish"),
    "dv": (u"ދިވެހި", u"Divehi, Dhivehi, Maldivian"),
    "nl": (u"Nederlands, Vlaams", u"Dutch, Flemish"),
    "dz": (u"རྫོང་ཁ", u"Dzongkha"),
    "en": (u"English", u"English"),
    "eo": (u"Esperanto", u"Esperanto"),
    "et": (u"eesti, eesti keel", u"Estonian"),
    "ee": (u"Eʋegbe", u"Ewe"),
    "fo": (u"føroyskt", u"Faroese"),
    "fj": (u"vosa Vakaviti", u"Fijian"),
    "fi": (u"suomi, suomen kieli", u"Finnish"),
    "fr": (u"français, langue française", u"French"),
    "ff": (u"Fulfulde, Pulaar, Pular", u"Fulah"),
    "gl": (u"Galego", u"Galician"),
    "ka": (u"ქართული", u"Georgian"),
    "de": (u"Deutsch", u"German"),
    "el": (u"ελληνικά", u"Greek (modern)"),
    "gn": (u"Avañe'ẽ", u"Guaraní"),
    "gu": (u"ગુજરાતી", u"Gujarati"),
    "ht": (u"Kreyòl ayisyen", u"Haitian, Haitian Creole"),
    "ha": (u"(Hausa) هَوُسَ", u"Hausa"),
    "he": (u"עברית", u"Hebrew (modern)"),
    "hz": (u"Otjiherero", u"Herero"),
    "hi": (u"हिन्दी, हिंदी", u"Hindi"),
    "ho": (u"Hiri Motu", u"Hiri Motu"),
    "hu": (u"magyar", u"Hungarian"),
    "ia": (u"Interlingua", u"Interlingua"),
    "id": (u"Bahasa Indonesia", u"Indonesian"),
    "ie": (u"Originally called Occidental; then Interlingue after WWII", u"Interlingue"),
    "ga": (u"Gaeilge", u"Irish"),
    "ig": (u"Asụsụ Igbo", u"Igbo"),
    "ik": (u"Iñupiaq, Iñupiatun", u"Inupiaq"),
    "io": (u"Ido", u"Ido"),
    "is": (u"Íslenska", u"Icelandic"),
    "it": (u"Italiano", u"Italian"),
    "iu": (u"ᐃᓄᒃᑎᑐᑦ", u"Inuktitut"),
    "ja": (u"日本語 (にほんご)", u"Japanese"),
    "jv": (u"ꦧꦱꦗꦮ, Basa Jawa", u"Javanese"),
    "kl": (u"kalaallisut, kalaallit oqaasii", u"Kalaallisut, Greenlandic"),
    "kn": (u"ಕನ್ನಡ", u"Kannada"),
    "kr": (u"Kanuri", u"Kanuri"),
    "ks": (u"कश्मीरी, كشميري‎", u"Kashmiri"),
    "kk": (u"қазақ тілі", u"Kazakh"),
    "km": (u"ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ", u"Central Khmer"),
    "ki": (u"Gĩkũyũ", u"Kikuyu, Gikuyu"),
    "rw": (u"Ikinyarwanda", u"Kinyarwanda"),
    "ky": (u"Кыргызча, Кыргыз тили", u"Kirghiz, Kyrgyz"),
    "kv": (u"коми кыв", u"Komi"),
    "kg": (u"Kikongo", u"Kongo"),
    "ko": (u"한국어", u"Korean"),
    "ku": (u"Kurdî, کوردی‎", u"Kurdish"),
    "kj": (u"Kuanyama", u"Kuanyama, Kwanyama"),
    "la": (u"latine, lingua latina", u"Latin"),
    "lb": (u"Lëtzebuergesch", u"Luxembourgish, Letzeburgesch"),
    "lg": (u"Luganda", u"Ganda"),
    "li": (u"Limburgs", u"Limburgan, Limburger, Limburgish"),
    "ln": (u"Lingála", u"Lingala"),
    "lo": (u"ພາສາລາວ", u"Lao"),
    "lt": (u"lietuvių kalba", u"Lithuanian"),
    "lu": (u"Kiluba", u"Luba-Katanga"),
    "lv": (u"latviešu valoda", u"Latvian"),
    "gv": (u"Gaelg, Gailck", u"Manx"),
    "mk": (u"македонски јазик", u"Macedonian"),
    "mg": (u"fiteny malagasy", u"Malagasy"),
    "ms": (u"Bahasa Melayu, بهاس ملايو‎", u"Malay"),
    "ml": (u"മലയാളം", u"Malayalam"),
    "mt": (u"Malti", u"Maltese"),
    "mi": (u"te reo Māori", u"Maori"),
    "mr": (u"मराठी", u"Marathi"),
    "mh": (u"Kajin M̧ajeļ", u"Marshallese"),
    "mn": (u"Монгол хэл", u"Mongolian"),
    "na": (u"Dorerin Naoero", u"Nauru"),
    "nv": (u"Diné bizaad", u"Navajo, Navaho"),
    "nd": (u"isiNdebele", u"North Ndebele"),
    "ne": (u"नेपाली", u"Nepali"),
    "ng": (u"Owambo", u"Ndonga"),
    "nb": (u"Norsk Bokmål", u"Norwegian Bokmål"),
    "nn": (u"Norsk Nynorsk", u"Norwegian Nynorsk"),
    "no": (u"Norsk", u"Norwegian"),
    "ii": (u"ꆈꌠ꒿ Nuosuhxop", u"Sichuan Yi, Nuosu"),
    "nr": (u"isiNdebele", u"South Ndebele"),
    "oc": (u"occitan, lenga d'òc", u"Occitan"),
    "oj": (u"ᐊᓂᔑᓈᐯᒧᐎᓐ", u"Ojibwa"),
    "cu": (u"ѩзыкъ словѣньскъ", u"Church Slavic, Church Slavonic, Old Church Slavonic, Old Slavonic, Old Bulgarian"),
    "om": (u"Afaan Oromoo", u"Oromo"),
    "or": (u"ଓଡ଼ିଆ", u"Oriya"),
    "os": (u"ирон æвзаг", u"Ossetian, Ossetic"),
    "pa": (u"ਪੰਜਾਬੀ", u"Panjabi, Punjabi"),
    "pi": (u"पाऴि", u"Pali"),
    "fa": (u"فارسی", u"Persian"),
    "pl": (u"język polski, polszczyzna", u"Polish"),
    "ps": (u"پښتو", u"Pashto, Pushto"),
    "pt": (u"Português", u"Portuguese"),
    "qu": (u"Runa Simi, Kichwa", u"Quechua"),
    "rm": (u"Rumantsch Grischun", u"Romansh"),
    "rn": (u"Ikirundi", u"Rundi"),
    "ro": (u"Română", u"Romanian, Moldavian, Moldovan"),
    "ru": (u"русский", u"Russian"),
    "sa": (u"संस्कृतम्", u"Sanskrit"),
    "sc": (u"sardu", u"Sardinian"),
    "sd": (u"सिन्धी, سنڌي، سندھی‎", u"Sindhi"),
    "se": (u"Davvisámegiella", u"Northern Sami"),
    "sm": (u"gagana fa'a Samoa", u"Samoan"),
    "sg": (u"yângâ tî sängö", u"Sango"),
    "sr": (u"српски језик", u"Serbian"),
    "gd": (u"Gàidhlig", u"Gaelic, Scottish Gaelic"),
    "sn": (u"chiShona", u"Shona"),
    "si": (u"සිංහල", u"Sinhala, Sinhalese"),
    "sk": (u"Slovenčina, Slovenský Jazyk", u"Slovak"),
    "sl": (u"Slovenski Jezik, Slovenščina", u"Slovene"),
    "so": (u"Soomaaliga, af Soomaali", u"Somali"),
    "st": (u"Sesotho", u"Southern Sotho"),
    "es": (u"Español", u"Spanish, Castilian"),
    "su": (u"Basa Sunda", u"Sundanese"),
    "sw": (u"Kiswahili", u"Swahili"),
    "ss": (u"SiSwati", u"Swati"),
    "sv": (u"Svenska", u"Swedish"),
    "ta": (u"தமிழ்", u"Tamil"),
    "te": (u"తెలుగు", u"Telugu"),
    "tg": (u"тоҷикӣ, toçikī, تاجیکی‎", u"Tajik"),
    "th": (u"ไทย", u"Thai"),
    "ti": (u"ትግርኛ", u"Tigrinya"),
    "bo": (u"བོད་ཡིག", u"Tibetan"),
    "tk": (u"Türkmen, Түркмен", u"Turkmen"),
    "tl": (u"Wikang Tagalog", u"Tagalog"),
    "tn": (u"Setswana", u"Tswana"),
    "to": (u"Faka Tonga", u"Tongan (Tonga Islands)"),
    "tr": (u"Türkçe", u"Turkish"),
    "ts": (u"Xitsonga", u"Tsonga"),
    "tt": (u"татар теле, tatar tele", u"Tatar"),
    "tw": (u"Twi", u"Twi"),
    "ty": (u"Reo Tahiti", u"Tahitian"),
    "ug": (u"ئۇيغۇرچە‎, Uyghurche", u"Uighur, Uyghur"),
    "uk": (u"Українська", u"Ukrainian"),
    "ur": (u"اردو", u"Urdu"),
    "uz": (u"Oʻzbek, Ўзбек, أۇزبېك‎", u"Uzbek"),
    "ve": (u"Tshivenḓa", u"Venda"),
    "vi": (u"Tiếng Việt", u"Vietnamese"),
    "vo": (u"Volapük", u"Volapük"),
    "wa": (u"Walon", u"Walloon"),
    "cy": (u"Cymraeg", u"Welsh"),
    "wo": (u"Wollof", u"Wolof"),
    "fy": (u"Frysk", u"Western Frisian"),
    "xh": (u"isiXhosa", u"Xhosa"),
    "yi": (u"ייִדיש", u"Yiddish"),
    "yo": (u"Yorùbá", u"Yoruba"),
    "za": (u"Saɯ cueŋƅ, Saw cuengh", u"Zhuang, Chuang"),
    "zu": (u"isiZulu", u"Zulu"),
}
