# coding=utf-8

# Source: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes, 10 Dec 2018
# Pares são (nome original, nome ISO)

LANG_NAMES = {
    "ab": ("аҧсуа бызшәа, аҧсшәа", "Abkhazian"),
    "aa": ("Afaraf", "Afar"),
    "af": ("Afrikaans", "Afrikaans"),
    "ak": ("Akan", "Akan"),
    "sq": ("Shqip", "Albanian"),
    "am": ("አማርኛ", "Amharic"),
    "ar": ("العربية", "Arabic"),
    "an": ("aragonés", "Aragonese"),
    "hy": ("Հայերեն", "Armenian"),
    "as": ("অসমীয়া", "Assamese"),
    "av": ("авар мацӀ, магӀарул мацӀ", "Avaric"),
    "ae": ("avesta", "Avestan"),
    "ay": ("aymar aru", "Aymara"),
    "az": ("azərbaycan dili", "Azerbaijani"),
    "bm": ("bamanankan", "Bambara"),
    "ba": ("башҡорт теле", "Bashkir"),
    "eu": ("euskara, euskera", "Basque"),
    "be": ("беларуская мова", "Belarusian"),
    "bn": ("বাংলা", "Bengali"),
    "bh": ("भोजपुरी", "Bihari languages"),
    "bi": ("Bislama", "Bislama"),
    "bs": ("bosanski jezik", "Bosnian"),
    "br": ("brezhoneg", "Breton"),
    "bg": ("български език", "Bulgarian"),
    "my": ("ဗမာစာ", "Burmese"),
    "ca": ("català, valencià", "Catalan, Valencian"),
    "ch": ("Chamoru", "Chamorro"),
    "ce": ("нохчийн мотт", "Chechen"),
    "ny": ("chiCheŵa, chinyanja", "Chichewa, Chewa, Nyanja"),
    "zh": ("中文 (Zhōngwén), 汉语, 漢語", "Chinese"),
    "cv": ("чӑваш чӗлхи", "Chuvash"),
    "kw": ("Kernewek", "Cornish"),
    "co": ("corsu, lingua corsa", "Corsican"),
    "cr": ("ᓀᐦᐃᔭᐍᐏᐣ", "Cree"),
    "hr": ("hrvatski jezik", "Croatian"),
    "cs": ("čeština, český jazyk", "Czech"),
    "da": ("dansk", "Danish"),
    "dv": ("ދިވެހި", "Divehi, Dhivehi, Maldivian"),
    "nl": ("Nederlands, Vlaams", "Dutch, Flemish"),
    "dz": ("རྫོང་ཁ", "Dzongkha"),
    "en": ("English", "English"),
    "eo": ("Esperanto", "Esperanto"),
    "et": ("eesti, eesti keel", "Estonian"),
    "ee": ("Eʋegbe", "Ewe"),
    "fo": ("føroyskt", "Faroese"),
    "fj": ("vosa Vakaviti", "Fijian"),
    "fi": ("suomi, suomen kieli", "Finnish"),
    "fr": ("français, langue française", "French"),
    "ff": ("Fulfulde, Pulaar, Pular", "Fulah"),
    "gl": ("Galego", "Galician"),
    "ka": ("ქართული", "Georgian"),
    "de": ("Deutsch", "German"),
    "el": ("ελληνικά", "Greek (modern)"),
    "gn": ("Avañe'ẽ", "Guaraní"),
    "gu": ("ગુજરાતી", "Gujarati"),
    "ht": ("Kreyòl ayisyen", "Haitian, Haitian Creole"),
    "ha": ("(Hausa) هَوُسَ", "Hausa"),
    "he": ("עברית", "Hebrew (modern)"),
    "hz": ("Otjiherero", "Herero"),
    "hi": ("हिन्दी, हिंदी", "Hindi"),
    "ho": ("Hiri Motu", "Hiri Motu"),
    "hu": ("magyar", "Hungarian"),
    "ia": ("Interlingua", "Interlingua"),
    "id": ("Bahasa Indonesia", "Indonesian"),
    "ie": ("Originally called Occidental; then Interlingue after WWII", "Interlingue"),
    "ga": ("Gaeilge", "Irish"),
    "ig": ("Asụsụ Igbo", "Igbo"),
    "ik": ("Iñupiaq, Iñupiatun", "Inupiaq"),
    "io": ("Ido", "Ido"),
    "is": ("Íslenska", "Icelandic"),
    "it": ("Italiano", "Italian"),
    "iu": ("ᐃᓄᒃᑎᑐᑦ", "Inuktitut"),
    "ja": ("日本語 (にほんご)", "Japanese"),
    "jv": ("ꦧꦱꦗꦮ, Basa Jawa", "Javanese"),
    "kl": ("kalaallisut, kalaallit oqaasii", "Kalaallisut, Greenlandic"),
    "kn": ("ಕನ್ನಡ", "Kannada"),
    "kr": ("Kanuri", "Kanuri"),
    "ks": ("कश्मीरी, كشميري‎", "Kashmiri"),
    "kk": ("қазақ тілі", "Kazakh"),
    "km": ("ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ", "Central Khmer"),
    "ki": ("Gĩkũyũ", "Kikuyu, Gikuyu"),
    "rw": ("Ikinyarwanda", "Kinyarwanda"),
    "ky": ("Кыргызча, Кыргыз тили", "Kirghiz, Kyrgyz"),
    "kv": ("коми кыв", "Komi"),
    "kg": ("Kikongo", "Kongo"),
    "ko": ("한국어", "Korean"),
    "ku": ("Kurdî, کوردی‎", "Kurdish"),
    "kj": ("Kuanyama", "Kuanyama, Kwanyama"),
    "la": ("latine, lingua latina", "Latin"),
    "lb": ("Lëtzebuergesch", "Luxembourgish, Letzeburgesch"),
    "lg": ("Luganda", "Ganda"),
    "li": ("Limburgs", "Limburgan, Limburger, Limburgish"),
    "ln": ("Lingála", "Lingala"),
    "lo": ("ພາສາລາວ", "Lao"),
    "lt": ("lietuvių kalba", "Lithuanian"),
    "lu": ("Kiluba", "Luba-Katanga"),
    "lv": ("latviešu valoda", "Latvian"),
    "gv": ("Gaelg, Gailck", "Manx"),
    "mk": ("македонски јазик", "Macedonian"),
    "mg": ("fiteny malagasy", "Malagasy"),
    "ms": ("Bahasa Melayu, بهاس ملايو‎", "Malay"),
    "ml": ("മലയാളം", "Malayalam"),
    "mt": ("Malti", "Maltese"),
    "mi": ("te reo Māori", "Maori"),
    "mr": ("मराठी", "Marathi"),
    "mh": ("Kajin M̧ajeļ", "Marshallese"),
    "mn": ("Монгол хэл", "Mongolian"),
    "na": ("Dorerin Naoero", "Nauru"),
    "nv": ("Diné bizaad", "Navajo, Navaho"),
    "nd": ("isiNdebele", "North Ndebele"),
    "ne": ("नेपाली", "Nepali"),
    "ng": ("Owambo", "Ndonga"),
    "nb": ("Norsk Bokmål", "Norwegian Bokmål"),
    "nn": ("Norsk Nynorsk", "Norwegian Nynorsk"),
    "no": ("Norsk", "Norwegian"),
    "ii": ("ꆈꌠ꒿ Nuosuhxop", "Sichuan Yi, Nuosu"),
    "nr": ("isiNdebele", "South Ndebele"),
    "oc": ("occitan, lenga d'òc", "Occitan"),
    "oj": ("ᐊᓂᔑᓈᐯᒧᐎᓐ", "Ojibwa"),
    "cu": (
        "ѩзыкъ словѣньскъ",
        "Church Slavic, Church Slavonic, Old Church Slavonic, Old Slavonic, Old Bulgarian",
    ),
    "om": ("Afaan Oromoo", "Oromo"),
    "or": ("ଓଡ଼ିଆ", "Oriya"),
    "os": ("ирон æвзаг", "Ossetian, Ossetic"),
    "pa": ("ਪੰਜਾਬੀ", "Panjabi, Punjabi"),
    "pi": ("पाऴि", "Pali"),
    "fa": ("فارسی", "Persian"),
    "pl": ("język polski, polszczyzna", "Polish"),
    "ps": ("پښتو", "Pashto, Pushto"),
    "pt": ("Português", "Portuguese"),
    "qu": ("Runa Simi, Kichwa", "Quechua"),
    "rm": ("Rumantsch Grischun", "Romansh"),
    "rn": ("Ikirundi", "Rundi"),
    "ro": ("Română", "Romanian, Moldavian, Moldovan"),
    "ru": ("русский", "Russian"),
    "sa": ("संस्कृतम्", "Sanskrit"),
    "sc": ("sardu", "Sardinian"),
    "sd": ("सिन्धी, سنڌي، سندھی‎", "Sindhi"),
    "se": ("Davvisámegiella", "Northern Sami"),
    "sm": ("gagana fa'a Samoa", "Samoan"),
    "sg": ("yângâ tî sängö", "Sango"),
    "sr": ("српски језик", "Serbian"),
    "gd": ("Gàidhlig", "Gaelic, Scottish Gaelic"),
    "sn": ("chiShona", "Shona"),
    "si": ("සිංහල", "Sinhala, Sinhalese"),
    "sk": ("Slovenčina, Slovenský Jazyk", "Slovak"),
    "sl": ("Slovenski Jezik, Slovenščina", "Slovene"),
    "so": ("Soomaaliga, af Soomaali", "Somali"),
    "st": ("Sesotho", "Southern Sotho"),
    "es": ("Español", "Spanish, Castilian"),
    "su": ("Basa Sunda", "Sundanese"),
    "sw": ("Kiswahili", "Swahili"),
    "ss": ("SiSwati", "Swati"),
    "sv": ("Svenska", "Swedish"),
    "ta": ("தமிழ்", "Tamil"),
    "te": ("తెలుగు", "Telugu"),
    "tg": ("тоҷикӣ, toçikī, تاجیکی‎", "Tajik"),
    "th": ("ไทย", "Thai"),
    "ti": ("ትግርኛ", "Tigrinya"),
    "bo": ("བོད་ཡིག", "Tibetan"),
    "tk": ("Türkmen, Түркмен", "Turkmen"),
    "tl": ("Wikang Tagalog", "Tagalog"),
    "tn": ("Setswana", "Tswana"),
    "to": ("Faka Tonga", "Tongan (Tonga Islands)"),
    "tr": ("Türkçe", "Turkish"),
    "ts": ("Xitsonga", "Tsonga"),
    "tt": ("татар теле, tatar tele", "Tatar"),
    "tw": ("Twi", "Twi"),
    "ty": ("Reo Tahiti", "Tahitian"),
    "ug": ("ئۇيغۇرچە‎, Uyghurche", "Uighur, Uyghur"),
    "uk": ("Українська", "Ukrainian"),
    "ur": ("اردو", "Urdu"),
    "uz": ("Oʻzbek, Ўзбек, أۇزبېك‎", "Uzbek"),
    "ve": ("Tshivenḓa", "Venda"),
    "vi": ("Tiếng Việt", "Vietnamese"),
    "vo": ("Volapük", "Volapük"),
    "wa": ("Walon", "Walloon"),
    "cy": ("Cymraeg", "Welsh"),
    "wo": ("Wollof", "Wolof"),
    "fy": ("Frysk", "Western Frisian"),
    "xh": ("isiXhosa", "Xhosa"),
    "yi": ("ייִדיש", "Yiddish"),
    "yo": ("Yorùbá", "Yoruba"),
    "za": ("Saɯ cueŋƅ, Saw cuengh", "Zhuang, Chuang"),
    "zu": ("isiZulu", "Zulu"),
}


def get_original_lang_name(code):
    return LANG_NAMES.get(code, (None, code))[0]


def display_original_lang_name(code):
    name = get_original_lang_name(code)
    if name is None:
        return code
    name = name.capitalize()
    if "," in name:
        return name.split(",")[0]
    return name
